version: '3'

services:
  api:
    image: php
    volumes:
      - .:/app
    ports:
      - 8000:8000
    expose:
      - 8000
    entrypoint: '/app/artisan'
    command: 'serve --host=0.0.0.0 --port=8000'
